version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rh_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rh_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rh_user -d rh_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1000:1000"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: